#!/usr/bin/env bash
# This script
if [ "$#" -le 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StricktHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
