#!/usr/bin/env bash
# This script installs nginx on a server with bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
string="\\\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $string" /etc/nginx/sites-enabled/default
sudo service nginx restart
