#!/usr/bin/env bash
# This script installs nginx on a server with bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=ccrhTmWurvQ permanent;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/error.html
error="\\\terror_page 404 ^/error;\nlocation= ^/error.html {\nroot /var/www/html; \ninternal;\n}"
sudo sed -i "43i $error" /etc/nginx/sites-enabled/default
sudo service nginx restart
