#!/usr/bin/env bash
# This script installs nginx on a server with bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=ccrhTmWurvQ permanent;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i 'error_page 404 /404.html' /etc/nginx/sites-enabled/default
sudo service nginx restart
