#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=ccrhTmWurvQ permanent;' /etc/nginx/sites-enabled/default
error="\\\terror_page 404 ^/custom_404.html;\nlocation = ^/xyz {\nroot /var/www/html; \ninternal;\n}"
sudo sed -i "43i $error" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
directfile="/etc/nginx/sites-available/default"
sudo sed -i "42i \\\tadd_header X-Served-By $HOSTNAME;\n" $directfile
sudo sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sudo service nginx restart
