#!/usr/bin/env bash
# This script configures a balance loader with roundrobin algo for this server
# to connect to two specified servers
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*

echo "backend web-backend
      balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server web1 35.243.156.189:80 check
    server web2 104.196.36.41:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "listen  http-incoming
    bind *:80
    stats uri /haproxy?stats
    default_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
