#!/usr/bin/env bash
# This script configures a balance loader with roundrobin algo for this server
# to connect to two specified servers

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get update
sudo apt-get -y install haproxy

sudo echo "
frontend localnodes
        bind *:80
        stats uri /haproxy
        default_backend data
backend data
        balance roundrobin
        server 873-web-01 35.229.80.211:80 check
        server 873-web-02 3.85.226.144:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
