#!/usr/bin/env bash
# This script configures a balance loader with roundrobin algo for this server
# to connect to two specified servers

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get update
sudo apt-get -y install haproxy

echo "frontend http-incoming
    bind *:80
    stats uri /haproxy
    default_backend web-backend

    backend web-backend
    balance roundrobin
    server 873-web-01 35.243.156.189 check
    server 873-web-02 104.196.36.41 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
