#!usr/bin/env bash
# This script configures nginx to listen on all with port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen [::]:80 ipv6only=off;' /etc/nginx/sites-enabled/default
sudo service nginx restart
