#!/usr/bin/env bash
# This script creates a file with its own PID, displays text and echoes based on signal passed

trap ok SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap delete SIGQUIT

delete(){
    rm /var/run/holbertonscript.pid
    exit 1
}

ok(){
    echo "I hate the kill command"
    rm /var/run/holbertonscript.pid
    exit 1
}

echo $BASHPID >> /var/run/holbertonscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
