#!/usr/bin/env bash
# This script prints Holberton School unless num is 4 or 8.
num=1
while [ $num -lt 11 ]
do
    if [ $num -eq 4 ]
    then
	echo "bad luck"
    elif [ $num -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((num++))
done
