#!/usr/bin/env bash
# This script gives you information about the holbertonschool file.
HS="./holbertonschool"
if [ -e "$HS" ]
then
    echo "holbertonschool file exists"
    if [ -s "$HS" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$HS" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
